pipeline {
    agent any

    environment {
        IMAGE_NAME = "bhupendra/devops-app"
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Cloning repository..."
                checkout scm
            }
        }

        stage('Validate Structure') {
            steps {
                sh '''
                [ -d app ] || exit 1
                [ -f docker/Dockerfile ] || exit 1
                [ -f docker/docker-compose.yml ] || exit 1
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $IMAGE_NAME:latest -f docker/Dockerfile .
                '''
            }
        }

        stage('Run Container (Test)') {
            steps {
                sh '''
                docker rm -f devops-test || true

                docker run -d \
                  --name devops-test \
                  -p 8090:80 \
                  $IMAGE_NAME:latest

                sleep 5

                CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' devops-test)

                curl -f http://$CONTAINER_IP || exit 1
                '''
            }
        }

        stage('Cleanup') {
            steps {
                sh 'docker rm -f devops-test || true'
            }
        }
    }

    post {
        success {
            echo "Pipeline SUCCESS"
        }
        failure {
            echo "Pipeline FAILED"
        }
    }
}
